pipeline:
  - name: SpacyNLP
    model: en_core_web_md
    case_sensitive: false
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
    pooling: mean
    alias: convert
  - name: RegexFeaturizer
    alias: regex
  - name: LexicalSyntacticFeaturizer
    alias: lexical-syntactic
  - name: CountVectorsFeaturizer
    alias: cvf-word
  - name: CountVectorsFeaturizer
    alias: cvf-char
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 50
  - name: EntitySynonymMapper
  - name: ResponseSelector
    featurizers:
      - convert
      - cvf-word
    epochs: 50
  - name: DucklingHTTPExtractor
    url: 'http://localhost:8000'
    dimensions:
      - amount-of-money
      - time
    timezone: Asia/Ho_Chi_Minh
    timeout: 3
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1
language: en
policies:
  - name: TEDPolicy
    max_history: 3
    epochs: 50
    model_confidence: linear_norm
  - name: FormPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.7
    core_fallback_action_name: utter_fallback
